# Generated by Django 3.1 on 2020-08-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_image_url', models.ImageField(blank=True, null=True, upload_to='blog/images')),
                ('second_image_url', models.ImageField(blank=True, null=True, upload_to='blog/images')),
                ('third_image_url', models.ImageField(blank=True, null=True, upload_to='blog/images')),
                ('main_banner', models.ImageField(blank=True, null=True, upload_to='blog/images')),
            ],
        ),
    ]
