# Generated by Django 3.0.6 on 2020-06-19 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='s_no',
            new_name='comment_id',
        ),
    ]
