# Generated by Django 3.1 on 2020-08-16 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200816_0456'),
        ('blog', '0009_auto_20200703_2106'),
    ]

    operations = [
    ]
