# Generated by Django 3.1 on 2020-08-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_merge_20200816_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content_heading1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_heading2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='sub_heading',
            field=models.TextField(),
        ),
    ]
