# Generated by Django 3.1 on 2020-08-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200817_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='sub_heading',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='sub_heading_content',
            field=models.TextField(),
        ),
    ]
