# Generated by Django 3.1 on 2020-08-23 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=13)),
                ('query', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForgotPasswordOtp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, max_length=13)),
                ('otp', models.CharField(blank=True, max_length=8, null=True)),
                ('count', models.IntegerField(default=1, help_text='Number of OTP sent')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_validated', models.CharField(blank=True, choices=[('VF', 'Verified'), ('NF', 'Not Verified')], default='NF', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneOtp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, max_length=13)),
                ('otp', models.CharField(blank=True, max_length=8, null=True)),
                ('count', models.IntegerField(default=1, help_text='Number of OTP sent')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwoFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=200, null=True)),
                ('sender_id', models.CharField(blank=True, max_length=10, null=True)),
                ('template_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, max_length=13)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1)),
                ('birth_day', models.CharField(blank=True, max_length=2)),
                ('birth_month', models.CharField(blank=True, max_length=2)),
                ('birth_year', models.CharField(blank=True, max_length=4)),
                ('image', models.ImageField(default='home/images/no-profile-pic.png', upload_to='home/images')),
                ('credit', models.DecimalField(decimal_places=2, default='0', max_digits=1000)),
                ('is_verified', models.CharField(blank=True, choices=[('VF', 'Verified'), ('NVF', 'Not Verified')], default='NVF', max_length=4)),
                ('is_email_verified', models.CharField(blank=True, choices=[('VF', 'Verified'), ('NVF', 'Not Verified')], default='NVF', max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
