# Generated by Django 3.0.6 on 2020-06-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
