# Generated by Django 3.0.6 on 2020-06-23 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200622_0113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
