# Generated by Django 3.0.6 on 2020-06-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200625_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, upload_to='home/images'),
        ),
    ]
