# Generated by Django 3.0.6 on 2020-06-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20200626_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/static/home/img/no-profile-pic.png', null=True, upload_to='home/images'),
        ),
    ]
