# Generated by Django 3.0.6 on 2020-06-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20200626_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='home/images/no-profile-pic.png', null=True, upload_to='home/images'),
        ),
    ]
