# Generated by Django 3.0.6 on 2020-06-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20200626_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='home/images/no-profile-pic.png', upload_to='home/images'),
        ),
    ]
