# Generated by Django 3.0.6 on 2020-07-05 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='query',
        ),
    ]
