# Generated by Django 3.0.6 on 2020-07-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_profile_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=200, null=True)),
                ('sender_id', models.CharField(blank=True, max_length=10, null=True)),
                ('template_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
