# Generated by Django 3.0.6 on 2020-07-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_twofactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOtp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, max_length=13)),
                ('otp', models.CharField(blank=True, max_length=8, null=True)),
                ('count', models.IntegerField(default=0, help_text='Number of OTP sent')),
            ],
        ),
    ]
