# Generated by Django 3.0.6 on 2020-07-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_phoneotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
