# Generated by Django 3.0.6 on 2020-07-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_phoneotp_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='count',
            field=models.IntegerField(default=1, help_text='Number of OTP sent'),
        ),
    ]
