# Generated by Django 3.0.6 on 2020-07-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20200709_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordOtp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, max_length=13)),
                ('otp', models.CharField(blank=True, max_length=8, null=True)),
                ('count', models.IntegerField(default=1, help_text='Number of OTP sent')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
