# Generated by Django 3.0.6 on 2020-07-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_forgotpasswordotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpasswordotp',
            name='is_validated',
            field=models.CharField(blank=True, choices=[('VF', 'Verified'), ('NF', 'Not Verified')], default='NVF', max_length=2),
        ),
    ]
