# Generated by Django 3.0.6 on 2020-08-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20200713_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_email_verified',
            field=models.CharField(blank=True, choices=[('VF', 'Verified'), ('NVF', 'Not Verified')], default='NVF', max_length=4),
        ),
    ]
