# Generated by Django 3.1 on 2020-08-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_profile_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credit',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=1000),
        ),
    ]
