# Generated by Django 3.0.6 on 2020-07-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('first_image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('second_image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('third_image_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
