# Generated by Django 3.0.6 on 2020-06-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20200602_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=60)),
                ('mobile', models.CharField(default='', max_length=60)),
                ('query_message', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
