# Generated by Django 3.0.6 on 2020-07-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_bannerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_video_link', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bannerimage',
            name='name',
        ),
    ]
