# Generated by Django 3.1 on 2020-09-03 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='total_price',
        ),
    ]
