# Generated by Django 3.0.6 on 2020-07-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20200705_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerimage',
            old_name='first_image_url',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='bannerimage',
            name='second_image_url',
        ),
        migrations.RemoveField(
            model_name='bannerimage',
            name='third_image_url',
        ),
    ]
