# Generated by Django 3.1 on 2020-08-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20200821_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='fourth_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='shopping/images'),
        ),
    ]
