# Generated by Django 3.0.6 on 2020-06-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='mobile_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
