# Generated by Django 3.1 on 2020-09-04 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_wishlistitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_qty',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
