# Generated by Django 3.0.6 on 2020-06-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_ordersupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_price',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
