# Generated by Django 3.0.6 on 2020-07-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20200705_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytmkey',
            name='merchant_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paytmkey',
            name='merchant_key',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paytmkey',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
