# Generated by Django 3.0.6 on 2020-06-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_orders_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
