# Generated by Django 3.0.6 on 2020-06-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_auto_20200612_0326'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaytmKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('merchant_id', models.CharField(default='', max_length=50)),
                ('merchant_key', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
