# Generated by Django 3.0.6 on 2020-07-20 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ip',
        ),
    ]
