# Generated by Django 3.0.6 on 2020-06-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_paytmkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoRule',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('rulename', models.CharField(max_length=50)),
                ('promotext', models.CharField(max_length=20)),
                ('discount', models.IntegerField(default=0)),
            ],
        ),
    ]
