# Generated by Django 3.1 on 2020-09-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference_id',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
    ]
