# Generated by Django 3.0.6 on 2020-06-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_promorule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoRule',
        ),
    ]
