# Generated by Django 3.0.6 on 2020-07-21 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_remove_comment_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='subject',
        ),
    ]
