# Generated by Django 3.0.6 on 2020-07-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_remove_comment_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Not Delivered', 'Not Delivered')], default='Not Delivered', max_length=20),
        ),
    ]
