# Generated by Django 3.1 on 2020-09-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_order_payment_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sub_total',
        ),
        migrations.AddField(
            model_name='order',
            name='credits_used',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=1000, null=True),
        ),
    ]
