# Generated by Django 3.1 on 2020-09-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_auto_20200905_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Started', 'Started'), ('Abandoned', 'Abandoned'), ('Return', 'Return'), ('Finished', 'Finished')], default='Started', max_length=120),
        ),
    ]
