# Generated by Django 3.0.6 on 2020-07-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0016_auto_20200723_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersupdate',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
