# Generated by Django 3.1 on 2020-08-16 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0019_product_count_sold'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaytmKey',
        ),
    ]
