# Generated by Django 3.0.6 on 2020-06-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0020_auto_20200630_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cartproduct_items',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
