# Generated by Django 3.0.6 on 2020-06-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0024_auto_20200630_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cartproduct_items',
            new_name='cartitems_product',
        ),
        migrations.AddField(
            model_name='order',
            name='cartitems_quantity',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
