# Generated by Django 3.0.6 on 2020-06-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0025_auto_20200630_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cartitems_product',
            new_name='cartproduct_items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cartitems_quantity',
        ),
    ]
