# Generated by Django 3.0.6 on 2020-07-02 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0028_buyitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping.Buy'),
        ),
    ]
